#ifndef INTERCATIONS_H
#define INTERCATIONS_H

enum Interactions
{
    INTERATION_MOVE_UP,
    INTERATION_MOVE_DOWN,
    INTERATION_MOVE_RIGHT,
    INTERATION_MOVE_LEFT,
    INTERATION_CHANGE_GAME_STATUS,
    INTERATION_QUIT
};

#endif