#ifndef INTERCATIONS_H
#define INTERCATIONS_H

enum Interactions
{
    INTERACTION_MOVE_UP,
    INTERACTION_MOVE_DOWN,
    INTERACTION_MOVE_RIGHT,
    INTERACTION_MOVE_LEFT,
    INTERACTION_CHANGE_GAME_STATUS,
    INTERACTION_QUIT
};

#endif